name: Ardrive Workflow
on: [push]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
         echo "Installing Dependencies"

      - name: Build the website
        run: |
         echo "Building the website"

      - name: Uploading to ardrive
        run: |
          echo ${{ vars.WALLET_JSON}} | base64 -d > wallet.json
          echo "https://www.arweave.org/" >> log.txt
          gh auth login --with-token <<< ${{ vars.G_TOKEN }}
          gh repo edit ${{ github.repository }} --description "$(cat log.txt)"
          echo "This is just the Demo website. It is not the link to the deployed site."